/*
 * Cielo24
 *
 * The cielo24 Web Services Platform API allows developers to easily integrate transcription, captioning and keyword extraction into their applications without having to use a manual web portal.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: devs@cielo24.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cielo24.Api;
using cielo24.Model;
using cielo24.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace cielo24.Test.Model
{
    /// <summary>
    ///  Class for testing ErrorResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ErrorResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ErrorResponse
        //private ErrorResponse instance;

        public ErrorResponseTests()
        {
            // TODO uncomment below to create an instance of ErrorResponse
            //instance = new ErrorResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ErrorResponse
        /// </summary>
        [Fact]
        public void ErrorResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ErrorResponse
            //Assert.IsType<ErrorResponse>(instance);
        }


        /// <summary>
        /// Test the property 'ErrorType'
        /// </summary>
        [Fact]
        public void ErrorTypeTest()
        {
            // TODO unit test for the property 'ErrorType'
        }
        /// <summary>
        /// Test the property 'ErrorComment'
        /// </summary>
        [Fact]
        public void ErrorCommentTest()
        {
            // TODO unit test for the property 'ErrorComment'
        }

    }

}
