/*
 * Cielo24
 *
 * The cielo24 Web Services Platform API allows developers to easily integrate transcription, captioning and keyword extraction into their applications without having to use a manual web portal.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: devs@cielo24.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cielo24.Api;
using cielo24.Model;
using cielo24.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace cielo24.Test.Model
{
    /// <summary>
    ///  Class for testing JobInfoResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class JobInfoResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for JobInfoResponse
        //private JobInfoResponse instance;

        public JobInfoResponseTests()
        {
            // TODO uncomment below to create an instance of JobInfoResponse
            //instance = new JobInfoResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of JobInfoResponse
        /// </summary>
        [Fact]
        public void JobInfoResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" JobInfoResponse
            //Assert.IsType<JobInfoResponse>(instance);
        }


        /// <summary>
        /// Test the property 'JobId'
        /// </summary>
        [Fact]
        public void JobIdTest()
        {
            // TODO unit test for the property 'JobId'
        }
        /// <summary>
        /// Test the property 'JobName'
        /// </summary>
        [Fact]
        public void JobNameTest()
        {
            // TODO unit test for the property 'JobName'
        }
        /// <summary>
        /// Test the property 'MediaLengthSeconds'
        /// </summary>
        [Fact]
        public void MediaLengthSecondsTest()
        {
            // TODO unit test for the property 'MediaLengthSeconds'
        }
        /// <summary>
        /// Test the property 'ExternalId'
        /// </summary>
        [Fact]
        public void ExternalIdTest()
        {
            // TODO unit test for the property 'ExternalId'
        }
        /// <summary>
        /// Test the property 'Priority'
        /// </summary>
        [Fact]
        public void PriorityTest()
        {
            // TODO unit test for the property 'Priority'
        }
        /// <summary>
        /// Test the property 'Fidelity'
        /// </summary>
        [Fact]
        public void FidelityTest()
        {
            // TODO unit test for the property 'Fidelity'
        }
        /// <summary>
        /// Test the property 'JobStatus'
        /// </summary>
        [Fact]
        public void JobStatusTest()
        {
            // TODO unit test for the property 'JobStatus'
        }
        /// <summary>
        /// Test the property 'Options'
        /// </summary>
        [Fact]
        public void OptionsTest()
        {
            // TODO unit test for the property 'Options'
        }
        /// <summary>
        /// Test the property 'ReturnTargets'
        /// </summary>
        [Fact]
        public void ReturnTargetsTest()
        {
            // TODO unit test for the property 'ReturnTargets'
        }
        /// <summary>
        /// Test the property 'SourceLanguage'
        /// </summary>
        [Fact]
        public void SourceLanguageTest()
        {
            // TODO unit test for the property 'SourceLanguage'
        }
        /// <summary>
        /// Test the property 'TargetLanguage'
        /// </summary>
        [Fact]
        public void TargetLanguageTest()
        {
            // TODO unit test for the property 'TargetLanguage'
        }
        /// <summary>
        /// Test the property 'CreationDate'
        /// </summary>
        [Fact]
        public void CreationDateTest()
        {
            // TODO unit test for the property 'CreationDate'
        }
        /// <summary>
        /// Test the property 'StartDate'
        /// </summary>
        [Fact]
        public void StartDateTest()
        {
            // TODO unit test for the property 'StartDate'
        }
        /// <summary>
        /// Test the property 'DueDate'
        /// </summary>
        [Fact]
        public void DueDateTest()
        {
            // TODO unit test for the property 'DueDate'
        }
        /// <summary>
        /// Test the property 'CompletedDate'
        /// </summary>
        [Fact]
        public void CompletedDateTest()
        {
            // TODO unit test for the property 'CompletedDate'
        }
        /// <summary>
        /// Test the property 'ReturnDate'
        /// </summary>
        [Fact]
        public void ReturnDateTest()
        {
            // TODO unit test for the property 'ReturnDate'
        }
        /// <summary>
        /// Test the property 'AuthorizationDate'
        /// </summary>
        [Fact]
        public void AuthorizationDateTest()
        {
            // TODO unit test for the property 'AuthorizationDate'
        }
        /// <summary>
        /// Test the property 'JobDifficulty'
        /// </summary>
        [Fact]
        public void JobDifficultyTest()
        {
            // TODO unit test for the property 'JobDifficulty'
        }

    }

}
