/*
 * Cielo24
 *
 * The cielo24 Web Services Platform API allows developers to easily integrate transcription, captioning and keyword extraction into their applications without having to use a manual web portal.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: devs@cielo24.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cielo24.Api;
using cielo24.Model;
using cielo24.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace cielo24.Test.Model
{
    /// <summary>
    ///  Class for testing JobOptions
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class JobOptionsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for JobOptions
        //private JobOptions instance;

        public JobOptionsTests()
        {
            // TODO uncomment below to create an instance of JobOptions
            //instance = new JobOptions();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of JobOptions
        /// </summary>
        [Fact]
        public void JobOptionsInstanceTest()
        {
            // TODO uncomment below to test "IsType" JobOptions
            //Assert.IsType<JobOptions>(instance);
        }


        /// <summary>
        /// Test the property 'CustomerApprovalSteps'
        /// </summary>
        [Fact]
        public void CustomerApprovalStepsTest()
        {
            // TODO unit test for the property 'CustomerApprovalSteps'
        }
        /// <summary>
        /// Test the property 'CustomerApprovalTool'
        /// </summary>
        [Fact]
        public void CustomerApprovalToolTest()
        {
            // TODO unit test for the property 'CustomerApprovalTool'
        }
        /// <summary>
        /// Test the property 'CustomMetadata'
        /// </summary>
        [Fact]
        public void CustomMetadataTest()
        {
            // TODO unit test for the property 'CustomMetadata'
        }
        /// <summary>
        /// Test the property 'Notes'
        /// </summary>
        [Fact]
        public void NotesTest()
        {
            // TODO unit test for the property 'Notes'
        }
        /// <summary>
        /// Test the property 'ReturnIwp'
        /// </summary>
        [Fact]
        public void ReturnIwpTest()
        {
            // TODO unit test for the property 'ReturnIwp'
        }
        /// <summary>
        /// Test the property 'GenerateMediaIntelligenceIwp'
        /// </summary>
        [Fact]
        public void GenerateMediaIntelligenceIwpTest()
        {
            // TODO unit test for the property 'GenerateMediaIntelligenceIwp'
        }
        /// <summary>
        /// Test the property 'SpeakerId'
        /// </summary>
        [Fact]
        public void SpeakerIdTest()
        {
            // TODO unit test for the property 'SpeakerId'
        }
        /// <summary>
        /// Test the property 'AudioDescription'
        /// </summary>
        [Fact]
        public void AudioDescriptionTest()
        {
            // TODO unit test for the property 'AudioDescription'
        }
        /// <summary>
        /// Test the property 'OnScreenText'
        /// </summary>
        [Fact]
        public void OnScreenTextTest()
        {
            // TODO unit test for the property 'OnScreenText'
        }
        /// <summary>
        /// Test the property 'MusicLyrics'
        /// </summary>
        [Fact]
        public void MusicLyricsTest()
        {
            // TODO unit test for the property 'MusicLyrics'
        }
        /// <summary>
        /// Test the property 'CustomSpecialHandling'
        /// </summary>
        [Fact]
        public void CustomSpecialHandlingTest()
        {
            // TODO unit test for the property 'CustomSpecialHandling'
        }

    }

}
