/*
 * Cielo24
 *
 * The cielo24 Web Services Platform API allows developers to easily integrate transcription, captioning and keyword extraction into their applications without having to use a manual web portal.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: devs@cielo24.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cielo24.Api;
using cielo24.Model;
using cielo24.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace cielo24.Test.Model
{
    /// <summary>
    ///  Class for testing LoginResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LoginResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LoginResponse
        //private LoginResponse instance;

        public LoginResponseTests()
        {
            // TODO uncomment below to create an instance of LoginResponse
            //instance = new LoginResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LoginResponse
        /// </summary>
        [Fact]
        public void LoginResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" LoginResponse
            //Assert.IsType<LoginResponse>(instance);
        }


        /// <summary>
        /// Test the property 'ApiToken'
        /// </summary>
        [Fact]
        public void ApiTokenTest()
        {
            // TODO unit test for the property 'ApiToken'
        }

    }

}
