/*
 * Cielo24
 *
 * The cielo24 Web Services Platform API allows developers to easily integrate transcription, captioning and keyword extraction into their applications without having to use a manual web portal.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: devs@cielo24.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cielo24.Api;
using cielo24.Model;
using cielo24.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace cielo24.Test.Model
{
    /// <summary>
    ///  Class for testing LoginBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LoginBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LoginBody
        //private LoginBody instance;

        public LoginBodyTests()
        {
            // TODO uncomment below to create an instance of LoginBody
            //instance = new LoginBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LoginBody
        /// </summary>
        [Fact]
        public void LoginBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" LoginBody
            //Assert.IsType<LoginBody>(instance);
        }


        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Fact]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }
        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Fact]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }
        /// <summary>
        /// Test the property 'Securekey'
        /// </summary>
        [Fact]
        public void SecurekeyTest()
        {
            // TODO unit test for the property 'Securekey'
        }

    }

}
