/*
 * Cielo24
 *
 * The cielo24 Web Services Platform API allows developers to easily integrate transcription, captioning and keyword extraction into their applications without having to use a manual web portal.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: devs@cielo24.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cielo24.Api;
using cielo24.Model;
using cielo24.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace cielo24.Test.Model
{
    /// <summary>
    ///  Class for testing NewJobBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NewJobBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NewJobBody
        //private NewJobBody instance;

        public NewJobBodyTests()
        {
            // TODO uncomment below to create an instance of NewJobBody
            //instance = new NewJobBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NewJobBody
        /// </summary>
        [Fact]
        public void NewJobBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" NewJobBody
            //Assert.IsType<NewJobBody>(instance);
        }


        /// <summary>
        /// Test the property 'JobName'
        /// </summary>
        [Fact]
        public void JobNameTest()
        {
            // TODO unit test for the property 'JobName'
        }
        /// <summary>
        /// Test the property 'Language'
        /// </summary>
        [Fact]
        public void LanguageTest()
        {
            // TODO unit test for the property 'Language'
        }
        /// <summary>
        /// Test the property 'ExternalId'
        /// </summary>
        [Fact]
        public void ExternalIdTest()
        {
            // TODO unit test for the property 'ExternalId'
        }
        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Fact]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }
        /// <summary>
        /// Test the property 'Requestor'
        /// </summary>
        [Fact]
        public void RequestorTest()
        {
            // TODO unit test for the property 'Requestor'
        }
        /// <summary>
        /// Test the property 'Reference'
        /// </summary>
        [Fact]
        public void ReferenceTest()
        {
            // TODO unit test for the property 'Reference'
        }
        /// <summary>
        /// Test the property 'ExpectedSpeakers'
        /// </summary>
        [Fact]
        public void ExpectedSpeakersTest()
        {
            // TODO unit test for the property 'ExpectedSpeakers'
        }
        /// <summary>
        /// Test the property 'IsDuplicate'
        /// </summary>
        [Fact]
        public void IsDuplicateTest()
        {
            // TODO unit test for the property 'IsDuplicate'
        }

    }

}
