/*
 * Cielo24
 *
 * The cielo24 Web Services Platform API allows developers to easily integrate transcription, captioning and keyword extraction into their applications without having to use a manual web portal.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: devs@cielo24.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cielo24.Api;
using cielo24.Model;
using cielo24.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace cielo24.Test.Model
{
    /// <summary>
    ///  Class for testing PerformTranscriptionBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PerformTranscriptionBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PerformTranscriptionBody
        //private PerformTranscriptionBody instance;

        public PerformTranscriptionBodyTests()
        {
            // TODO uncomment below to create an instance of PerformTranscriptionBody
            //instance = new PerformTranscriptionBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PerformTranscriptionBody
        /// </summary>
        [Fact]
        public void PerformTranscriptionBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" PerformTranscriptionBody
            //Assert.IsType<PerformTranscriptionBody>(instance);
        }


        /// <summary>
        /// Test the property 'JobId'
        /// </summary>
        [Fact]
        public void JobIdTest()
        {
            // TODO unit test for the property 'JobId'
        }
        /// <summary>
        /// Test the property 'TranscriptionFidelity'
        /// </summary>
        [Fact]
        public void TranscriptionFidelityTest()
        {
            // TODO unit test for the property 'TranscriptionFidelity'
        }
        /// <summary>
        /// Test the property 'Priority'
        /// </summary>
        [Fact]
        public void PriorityTest()
        {
            // TODO unit test for the property 'Priority'
        }
        /// <summary>
        /// Test the property 'CallbackUrl'
        /// </summary>
        [Fact]
        public void CallbackUrlTest()
        {
            // TODO unit test for the property 'CallbackUrl'
        }
        /// <summary>
        /// Test the property 'Options'
        /// </summary>
        [Fact]
        public void OptionsTest()
        {
            // TODO unit test for the property 'Options'
        }
        /// <summary>
        /// Test the property 'TargetLanguage'
        /// </summary>
        [Fact]
        public void TargetLanguageTest()
        {
            // TODO unit test for the property 'TargetLanguage'
        }
        /// <summary>
        /// Test the property 'TurnaroundHours'
        /// </summary>
        [Fact]
        public void TurnaroundHoursTest()
        {
            // TODO unit test for the property 'TurnaroundHours'
        }

    }

}
