/*
 * Cielo24
 *
 * The cielo24 Web Services Platform API allows developers to easily integrate transcription, captioning and keyword extraction into their applications without having to use a manual web portal.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: devs@cielo24.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cielo24.Api;
using cielo24.Model;
using cielo24.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace cielo24.Test.Model
{
    /// <summary>
    ///  Class for testing PerformTranslationResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PerformTranslationResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PerformTranslationResponse
        //private PerformTranslationResponse instance;

        public PerformTranslationResponseTests()
        {
            // TODO uncomment below to create an instance of PerformTranslationResponse
            //instance = new PerformTranslationResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PerformTranslationResponse
        /// </summary>
        [Fact]
        public void PerformTranslationResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" PerformTranslationResponse
            //Assert.IsType<PerformTranslationResponse>(instance);
        }


        /// <summary>
        /// Test the property 'TranslationJobIds'
        /// </summary>
        [Fact]
        public void TranslationJobIdsTest()
        {
            // TODO unit test for the property 'TranslationJobIds'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

    }

}
