/*
 * Cielo24
 *
 * The cielo24 Web Services Platform API allows developers to easily integrate transcription, captioning and keyword extraction into their applications without having to use a manual web portal.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: devs@cielo24.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = cielo24.Client.OpenAPIDateConverter;

namespace cielo24.Model
{
    /// <summary>
    /// Defines IWPEnum
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum IWPEnum
    {
        /// <summary>
        /// Enum PREMIUM for value: PREMIUM
        /// </summary>
        [EnumMember(Value = "PREMIUM")]
        PREMIUM = 1,

        /// <summary>
        /// Enum INTERIMPROFESSIONAL for value: INTERIM_PROFESSIONAL
        /// </summary>
        [EnumMember(Value = "INTERIM_PROFESSIONAL")]
        INTERIMPROFESSIONAL = 2,

        /// <summary>
        /// Enum PROFESSIONAL for value: PROFESSIONAL
        /// </summary>
        [EnumMember(Value = "PROFESSIONAL")]
        PROFESSIONAL = 3,

        /// <summary>
        /// Enum SPEAKERID for value: SPEAKER_ID
        /// </summary>
        [EnumMember(Value = "SPEAKER_ID")]
        SPEAKERID = 4,

        /// <summary>
        /// Enum FINAL for value: FINAL
        /// </summary>
        [EnumMember(Value = "FINAL")]
        FINAL = 5,

        /// <summary>
        /// Enum MECHANICAL for value: MECHANICAL
        /// </summary>
        [EnumMember(Value = "MECHANICAL")]
        MECHANICAL = 6,

        /// <summary>
        /// Enum CUSTOMERAPPROVEDRETURN for value: CUSTOMER_APPROVED_RETURN
        /// </summary>
        [EnumMember(Value = "CUSTOMER_APPROVED_RETURN")]
        CUSTOMERAPPROVEDRETURN = 7,

        /// <summary>
        /// Enum CUSTOMERAPPROVEDTRANSLATION for value: CUSTOMER_APPROVED_TRANSLATION
        /// </summary>
        [EnumMember(Value = "CUSTOMER_APPROVED_TRANSLATION")]
        CUSTOMERAPPROVEDTRANSLATION = 8

    }

}
