/*
 * Cielo24
 *
 * The cielo24 Web Services Platform API allows developers to easily integrate transcription, captioning and keyword extraction into their applications without having to use a manual web portal.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: devs@cielo24.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = cielo24.Client.OpenAPIDateConverter;

namespace cielo24.Model
{
    /// <summary>
    /// PerformTranslationResponse
    /// </summary>
    [DataContract(Name = "PerformTranslationResponse")]
    public partial class PerformTranslationResponse : IEquatable<PerformTranslationResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PerformTranslationResponse" /> class.
        /// </summary>
        /// <param name="translationJobIds">translationJobIds.</param>
        /// <param name="message">message.</param>
        public PerformTranslationResponse(List<string> translationJobIds = default(List<string>), string message = default(string))
        {
            this.TranslationJobIds = translationJobIds;
            this.Message = message;
        }

        /// <summary>
        /// Gets or Sets TranslationJobIds
        /// </summary>
        [DataMember(Name = "translation_job_ids", EmitDefaultValue = false)]
        public List<string> TranslationJobIds { get; set; }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        [DataMember(Name = "message", EmitDefaultValue = false)]
        public string Message { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PerformTranslationResponse {\n");
            sb.Append("  TranslationJobIds: ").Append(TranslationJobIds).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PerformTranslationResponse);
        }

        /// <summary>
        /// Returns true if PerformTranslationResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of PerformTranslationResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PerformTranslationResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.TranslationJobIds == input.TranslationJobIds ||
                    this.TranslationJobIds != null &&
                    input.TranslationJobIds != null &&
                    this.TranslationJobIds.SequenceEqual(input.TranslationJobIds)
                ) && 
                (
                    this.Message == input.Message ||
                    (this.Message != null &&
                    this.Message.Equals(input.Message))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.TranslationJobIds != null)
                {
                    hashCode = (hashCode * 59) + this.TranslationJobIds.GetHashCode();
                }
                if (this.Message != null)
                {
                    hashCode = (hashCode * 59) + this.Message.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
